channels:
- conda-forge
dependencies:
- python=3.13.0
- pip<=25.2
- pip:
  - mlflow==3.3.1
  - cloudpickle==3.1.1
  - numpy==2.3.1
  - pandas==2.3.0
  - psutil==6.1.1
  - pyarrow==19.0.0
  - scikit-learn==1.7.1
  - scipy==1.16.0
  - xgboost==3.0.2
name: mlflow-env
